/** Skill taxonomy for the candidate skill picker (autocomplete suggestions). */
export const SKILL_TAXONOMY: readonly string[] = [
  'Angular',
  'React',
  'Vue.js',
  'TypeScript',
  'JavaScript',
  'HTML5',
  'CSS3',
  'SCSS',
  'RxJS',
  'Node.js',
  'Express.js',
  'NestJS',
  'Java',
  'Spring Boot',
  'C#',
  '.NET Core',
  'Python',
  'Django',
  'PHP',
  'Laravel',
  'Go',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'GraphQL',
  'REST API',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'Git',
  'CI/CD',
  'Jest',
  'Cypress',
  'Figma',
  'UI/UX Design',
  'Agile/Scrum',
  'Project Management',
  'Communication',
  'Leadership',
  'Problem Solving',
];
